version: '3'

services:
  flask:
    image: mpantelidakis/webapp-flask
    environment:
      # APP_ENV: "prod"
      APP_DEBUG: "False"
      # APP_PORT: 5000
      MONGODB_DATABASE: flaskdb
      # MONGODB_USERNAME: flaskuser
      # # Replace with env file l8er
      # MONGODB_PASSWORD: pwd
      # MONGODB_HOSTNAME: mongodb
    volumes:
      - media_volume:/vol/web/media
    links:
      - mongodb
      
  nginx:
    image: mpantelidakis/webapp-nginx
    volumes:
      - media_volume:/vol/web/media
    ports:
      - "5000:81"
    links:
      - flask
      
  mongodb:
    image: mpantelidakis/webapp-mongo
    restart: always
    environment:
      # MONGO_INITDB_ROOT_USERNAME: usr 
      # Replace with env file l8er
      # MONGO_INITDB_ROOT_PASSWORD: pwd
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
  
  react:
    image: mpantelidakis/webapp-react
    restart: always
    ports:
      - "8080:80"
volumes:
  mongodbdata:
  media_volume:
